### ISSUE TITLE
Support for css preprocessors

### ISSUE THREAD

**Issue by jgainfort** [filipesilva/rollup-plugin-angular-inline#2]
First I want to say thank you for creating this plugin! It works amazingly and solved a major problem I was facing with creating angular component libraries as the projects I dev tend to have larger html templates and use sass.

I want to propose a small addition to where the url's in the styleUrls property can have any extension but the plugin will assume there is a .css extension available.

Reasoning for this is currently my styleUrls would look something like this

`styleUrls: ['./sample.component.scss']`

but in order to accommodate for this plugin I need to change the extension for .css even though in my src there will never be a css file and its only available once the project goes through a build step.

If you have no objections I will open a PR.

**Comment by filipesilva** [comment]
Heya, to be honest I have pretty much abandoned this repo in favor of the build step found in https://github.com/filipesilva/angular-quickstart-lib.

This is because sourcemaps will likely be incorrect with this approach. I added a warning about this in https://github.com/filipesilva/rollup-plugin-angular-inline/commit/b00c1bc800d9d0ad054978aa3065b291809bbeff.
